spring.application.name=Apigateway
server.port=8080
spring.web.resources.add-mappings=false

# Circuit Breaker - Event Service
resilience4j.circuitbreaker.instances.eventService.slidingWindowSize=3
resilience4j.circuitbreaker.instances.eventService.failureRateThreshold=50
resilience4j.circuitbreaker.instances.eventService.waitDurationInOpenState=5000
resilience4j.circuitbreaker.instances.eventService.automaticTransitionFromOpenToHalfOpenEnabled=true

# Circuit Breaker - Auth Service
resilience4j.circuitbreaker.instances.authService.slidingWindowSize=3
resilience4j.circuitbreaker.instances.authService.failureRateThreshold=50
resilience4j.circuitbreaker.instances.authService.waitDurationInOpenState=5000
resilience4j.circuitbreaker.instances.authService.automaticTransitionFromOpenToHalfOpenEnabled=true